### ISSUE TITLE
[1.16.1] v5.0 Dedicated Server Crashes on Startup

### ISSUE THREAD

**Issue by jschmidt1224** [Squidsword/Ores-Above-Diamonds-Old#8]
When using v5.0 on a dedicated server, I get a crash at startup.
Using Forge 32.0.75.

Attaching latest.log and debug.log
[debug.log](https://github.com/Squidsword/Ores-Above-Diamonds-Old/files/4976369/debug.log)
[latest.log](https://github.com/Squidsword/Ores-Above-Diamonds-Old/files/4976370/latest.log)

**Comment by Squidsword** [comment]
Thanks for the report, I'll try to get a fix and I'll get back to you on this thread.

**Comment by jschmidt1224** [comment]
If you push the 1.16.1 source, I can take a look too if you'd like

**Comment by Squidsword** [comment]
Hey, I'm still getting the hang of Git and making branches for all the versions. I have the 1.16 version here https://github.com/Squidsword/OresAboveDiamondsTest5 . Beware, the code is generally really sloppy and a lot of stuff is hardcoded; I didn't have any programming knowledge when I started and am still cleaning up. Thank you for offering!

**Comment by Squidsword** [comment]
Hey, I had a chance to check and I think I found the problem, the method for registering the commands is different in the latest forge 1.16 version compared to the one I originally used. I found it and fixed it, I'll send a new version on curseforge soon. Again, thanks for reporting and let me know of any other problems.

**Comment by jschmidt1224** [comment]
No problem.

I found the fix to this issue.
Line 14 of ServerStartEventHandler should be
CommandConfigChange.register(event.getServer().getCommandManager().getDispatcher());

**Comment by Squidsword** [comment]
Hah lol, we found it at the exact same time. Yeah, that was the problem, I'll get it going right now but I'm in a League game with my friends so I'll do it when I finish. Enjoy the mod.

**Comment by Squidsword** [comment]
Just letting you know the new version has been approved!
